# Generated by Django 2.1.7 on 2019-03-12 16:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=128),
        ),
    ]
